kind: pipeline
name: arm-cargo-build
type: docker
steps:
  - name: build
    image: ubuntu:16.04
    volumes: #挂载卷
      - name: gcc
        path: /gcc
      - name: gosdk
        path: /go
      - name: gocache
        path: /root/go/pkg/mod/
    commands:
      - |
        echo "" >> config.yml
        echo "sha: ${DRONE_COMMIT_SHA}" >> config.yml
      - export PATH=$PATH:/go/bin/
      - export PATH=$PATH:/gcc/bin/
      - chmod +x build.sh
      - chmod +x updav
      - arm-linux-gnueabihf-gcc --version
      - go env -w GONOSUMDB=*
      #- export GOPROXY=http://mirrors.aliyun.com/goproxy/
      - sleep 1000
      - ./build.sh
      - tar -cvf cargo.tar runner upgrade.sh config.yml
      - version=$(head -n 3 config/version.go | tail -n 1 | cut -d '"' -f 2)
      - echo $version
      - ./updav -u http://192.168.8.6:8081 -a dev -p Az*29!#^1Nan -f cargo.tar -r /uchi/公交车/$version
  - name: scp-files
    image: appleboy/drone-scp:1.6
    settings:
      host: 192.168.8.13
      username: root
      password: root
      port: 22
      target: /uchi
      source:
       - config.yml
       - runner
       - upgrade.sh
#  - name: remote-runner
#    image: appleboy/drone-ssh:1.7
#    settings:
#      host:
#        - 192.168.8.39
#      username: root
#      password: root
#      port: 22
#      command_timeout: 5m
#      script:
#        - cd /hao88/app/cargo
#        - chmod +x runner
#        - touch runner
##        - ldconfig
#        - ldd ./runner
##        - sleep 2
##        - nohup ./runner &
##        - ./runner
#        - ls

volumes:
  - name: gcc
    host:
      path: /mnt/user/appdata/drone/tools/cargo/opt/EmbedSky/gcc-linaro-5.3.1-2016.05-x86_64_arm-linux-gnueabihf
  - name: gosdk
    host:
      path: /mnt/user/appdata/drone/tools/gosdk/go
  - name: gocache
    host:
      path: /mnt/user/appdata/drone/tools/cargo/gocache