kind: pipeline
name: arm-cargo-build
type: docker
steps:
  - name: build
    image: ubuntu:16.04
    volumes: #挂载卷
      - name: gcc
        path: /gcc
      - name: gosdk
        path: /go
#      - name: go-cache
#        path: /go/pkg/cache
    commands:

      - export PATH=$PATH:/go/bin/
      - export PATH=$PATH:/gcc/bin/
      - chmod +x build.sh
      - arm-linux-gnueabihf-gcc --version
      - go version
      - go env -w GONOSUMDB=*
      - export GOPROXY=http://mirrors.aliyun.com/goproxy/
      - ./build.sh
  - name: ssh
    image: appleboy/drone-ssh
    settings:
      host:
        - 192.168.8.39
      username: root
      password: root
      port: 22
      command_timeout: 5m
      script:
        - echo "Hello World"
        - scp
        - rz
#  - name: upload
#    image: appleboy/drone-scp
#    settings:
#      host:
#       - 192.168.8.39
#      username: root
#      password: root
#      source: /drone/src/cargo
#      target: /usr/app/cargo

volumes:
  - name: gcc
    host:
      path: /mnt/user/appdata/drone/tools/cargo/opt/EmbedSky/gcc-linaro-5.3.1-2016.05-x86_64_arm-linux-gnueabihf
  - name: gosdk
    host:
      path: /mnt/disk1/appdata/drone/tools/gosdk/go
#  - name: go-cache
#    host:
#      path: /mnt/disk1/appdata/drone/tools/cargo/go-cache