kind: pipeline
name: arm-cargo-build
type: docker
steps:
  - name: build
    image: ubuntu:16.04
    volumes: #挂载卷
      - name: gcc
        path: /gcc
      - name: gosdk
        path: /go
      - name: go-cache
        path: /go/pkg/cache
    commands:
      - export GCC=$GCC:/gcc/bin
      - export GOPATH=$GOPATH:/go/bin
      - ls -l
      - chmod +x build.sh
      - cd ..
      - ls -l
      - cd ..
      - ls -l
      - ls /go
      - ls /go/bin
      - cd /go/bin
      - ls
      - ./go version
      - ls /gcc
      - go version
      - ./build.sh
volumes:
  - name: gcc
    host:
      path: /mnt/user/appdata/drone/tools/cargo/opt/EmbedSky/gcc-linaro-5.3.1-2016.05-x86_64_arm-linux-gnueabihf
  - name: gosdk
    host:
      path: /mnt/disk1/appdata/drone/tools/gosdk/go
  - name: go-cache
    host:
      path: /mnt/disk1/appdata/drone/tools/cargo/go-cache