kind: pipeline
name: arm-cargo-build
type: docker
steps:
  - name: build
    image: ubuntu:16.04
    volumes: #挂载卷
      - name: gcc
        path: /gcc
      - name: gosdk
        path: /go
      - name: gocache
        path: /root/go/pkg/mod/
    commands:
      - bash
      - export PATH=$PATH:/go/bin/
      - export PATH=$PATH:/gcc/bin/
      - chmod +x build.sh
      - arm-linux-gnueabihf-gcc --version
      - go version
      - go env -w GONOSUMDB=*
      - export GOPROXY=http://mirrors.aliyun.com/goproxy/
      - ./build.sh
#      - sleep 36000
  - name: scp-file
    image: appleboy/drone-scp:1.6
    settings:
      host: 192.168.8.39
      username: root
      password: root
      port: 22
      target: /hao88/app/cargo
      source: runner
  - name: remote-runner
    image: appleboy/drone-ssh:1.7
    settings:
      host:
        - 192.168.8.39
      username: root
      password: root
      port: 22
      command_timeout: 5m
      script:
        - sleep 1
        - cd /hao88/app/cargo
        - chmod +x runner
        - touch runner
        - sleep 1
        - ldd ./runner
#        - ./runner
#        - ./runner & disown
        - ls
        - sleep 2
        - nohup ./runner &
        - ls
volumes:
  - name: gcc
    host:
      path: /mnt/user/appdata/drone/tools/cargo/opt/EmbedSky/gcc-linaro-5.3.1-2016.05-x86_64_arm-linux-gnueabihf
  - name: gosdk
    host:
      path: /mnt/disk1/appdata/drone/tools/gosdk/go
  - name: gocache
    host:
      path: /mnt/disk1/appdata/drone/tools/cargo/gocache