kind: pipeline
name: arm-cargo-build
type: docker
steps:
  - name: restore-cache # 加载缓存
    pull: if-not-exists # 如果镜像不存在则拉取,免去每次都要重新下载
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      restore: true
      mount:
        - ./cargo_mod
  - name: build
    image: ubuntu:16.04
    volumes: #挂载卷
      - name: gcc
        path: /gcc
      - name: gosdk
        path: /go
    #      - name: go-cache
    #        path: /go/pkg/cache
    commands:
      - bash
      - export PATH=$PATH:/go/bin/
      - export PATH=$PATH:/gcc/bin/
      - chmod +x build.sh
      - arm-linux-gnueabihf-gcc --version
      - go version
      - go env -w GONOSUMDB=*
      - export GOPROXY=http://mirrors.aliyun.com/goproxy/
      - ./build.sh
      - sleep 36000
  - name: scp-file
    image: appleboy/drone-scp
    settings:
      host: 192.168.8.39
      username: root
      password: root
      port: 22
      target: /hao88/app/cargo
      source: runner
  - name: remote-runner
    image: appleboy/drone-ssh
    settings:
      host:
        - 192.168.8.39
      username: root
      password: root
      port: 22
      command_timeout: 5m
      script:
        - cd /hao88/app/cargo
        - chmod +x runner
        - ldd ./runner
#        - ./runner
        - ./runner & disown
#        - nohup ./runner &
  - name: rebuild-cache   # 构建缓存
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      rebuild: true
      mount:
        - ./cargo_mod
volumes:
  - name: gcc
    host:
      path: /mnt/user/appdata/drone/tools/cargo/opt/EmbedSky/gcc-linaro-5.3.1-2016.05-x86_64_arm-linux-gnueabihf
  - name: gosdk
    host:
      path: /mnt/disk1/appdata/drone/tools/gosdk/go
  - name: cache
    host:
      path: /mnt/disk1/appdata/drone/tools/cargo/cache