kind: pipeline
name: arm-cargo-build
type: docker
steps:
  - name: build
    image: ubuntu:16.04
    volumes: #挂载卷
      - name: gcc
        path: /gcc
      - name: gosdk
        path: /go
#      - name: go-cache
#        path: /go/pkg/cache
    commands:
      - ls /go/bin
      - ls /gcc
      - export PATH=$PATH:/go/bin/
      - export PATH=$PATH:/gcc/bin/
      - go version
      - chmod +x build.sh
      - go version
      - arm-linux-gnueabihf-gcc --version
#      - go env -w GONOSUMDB=*
#      - export GOPROXY=http://mirrors.aliyun.com/goproxy/
#      - go clean -modcache
#      - go mod tidy
      #      - export GOPROXY=http://goprox.cn
      - ./build.sh
      - ls
volumes:
  - name: gcc
    host:
      path: /mnt/user/appdata/drone/tools/cargo/opt/EmbedSky/gcc-linaro-5.3.1-2016.05-x86_64_arm-linux-gnueabihf
  - name: gosdk
    host:
      path: /mnt/disk1/appdata/drone/tools/gosdk/go
#  - name: go-cache
#    host:
#      path: /mnt/disk1/appdata/drone/tools/cargo/go-cache