app:
  appname: cargo
  version: 1.3.8
  platform: 1

icbc:
  checkUrl: "https://www.tripgw.cn:9988"
  verifyUrl: "https://www.tripgw.cn:9988"
  CorpId: "2000001924"
  CorpId2: "2000001924"
  Bcss: BCSSHecsun0001
uchi:
  eqpcode: EQP20230629000001