// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.22.3
// source: emcs.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApiLogRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp       string `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	DeviceId        string `protobuf:"bytes,2,opt,name=deviceId,proto3" json:"deviceId,omitempty"`
	AppVersion      string `protobuf:"bytes,3,opt,name=appVersion,proto3" json:"appVersion,omitempty"`
	Type            string `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Status          uint32 `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	RequestUrl      string `protobuf:"bytes,6,opt,name=requestUrl,proto3" json:"requestUrl,omitempty"`
	RequestContent  string `protobuf:"bytes,7,opt,name=requestContent,proto3" json:"requestContent,omitempty"`
	ResponseContent string `protobuf:"bytes,8,opt,name=responseContent,proto3" json:"responseContent,omitempty"`
}

func (x *ApiLogRequest) Reset() {
	*x = ApiLogRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_emcs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApiLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiLogRequest) ProtoMessage() {}

func (x *ApiLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_emcs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiLogRequest.ProtoReflect.Descriptor instead.
func (*ApiLogRequest) Descriptor() ([]byte, []int) {
	return file_emcs_proto_rawDescGZIP(), []int{0}
}

func (x *ApiLogRequest) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *ApiLogRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *ApiLogRequest) GetAppVersion() string {
	if x != nil {
		return x.AppVersion
	}
	return ""
}

func (x *ApiLogRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ApiLogRequest) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ApiLogRequest) GetRequestUrl() string {
	if x != nil {
		return x.RequestUrl
	}
	return ""
}

func (x *ApiLogRequest) GetRequestContent() string {
	if x != nil {
		return x.RequestContent
	}
	return ""
}

func (x *ApiLogRequest) GetResponseContent() string {
	if x != nil {
		return x.ResponseContent
	}
	return ""
}

type ApiLogResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *ApiLogResp) Reset() {
	*x = ApiLogResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_emcs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApiLogResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiLogResp) ProtoMessage() {}

func (x *ApiLogResp) ProtoReflect() protoreflect.Message {
	mi := &file_emcs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiLogResp.ProtoReflect.Descriptor instead.
func (*ApiLogResp) Descriptor() ([]byte, []int) {
	return file_emcs_proto_rawDescGZIP(), []int{1}
}

func (x *ApiLogResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type NumUploadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceId  string `protobuf:"bytes,1,opt,name=deviceId,proto3" json:"deviceId,omitempty"`
	TimeStamp string `protobuf:"bytes,2,opt,name=timeStamp,proto3" json:"timeStamp,omitempty"`
	PeopleNum int32  `protobuf:"varint,3,opt,name=peopleNum,proto3" json:"peopleNum,omitempty"`
}

func (x *NumUploadRequest) Reset() {
	*x = NumUploadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_emcs_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NumUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumUploadRequest) ProtoMessage() {}

func (x *NumUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_emcs_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumUploadRequest.ProtoReflect.Descriptor instead.
func (*NumUploadRequest) Descriptor() ([]byte, []int) {
	return file_emcs_proto_rawDescGZIP(), []int{2}
}

func (x *NumUploadRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *NumUploadRequest) GetTimeStamp() string {
	if x != nil {
		return x.TimeStamp
	}
	return ""
}

func (x *NumUploadRequest) GetPeopleNum() int32 {
	if x != nil {
		return x.PeopleNum
	}
	return 0
}

type BasicResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *BasicResp) Reset() {
	*x = BasicResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_emcs_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BasicResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasicResp) ProtoMessage() {}

func (x *BasicResp) ProtoReflect() protoreflect.Message {
	mi := &file_emcs_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasicResp.ProtoReflect.Descriptor instead.
func (*BasicResp) Descriptor() ([]byte, []int) {
	return file_emcs_proto_rawDescGZIP(), []int{3}
}

func (x *BasicResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_emcs_proto protoreflect.FileDescriptor

var file_emcs_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x65, 0x6d, 0x63, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x65, 0x6d,
	0x63, 0x73, 0x22, 0x87, 0x02, 0x0a, 0x0d, 0x41, 0x70, 0x69, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x1e,
	0x0a, 0x0a, 0x61, 0x70, 0x70, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x61, 0x70, 0x70, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x55, 0x72, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x55, 0x72, 0x6c, 0x12, 0x26, 0x0a, 0x0e, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0e, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x12, 0x28, 0x0a, 0x0f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x72, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x26, 0x0a, 0x0a,
	0x41, 0x70, 0x69, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x22, 0x6a, 0x0a, 0x10, 0x4e, 0x75, 0x6d, 0x55, 0x70, 0x6c, 0x6f, 0x61,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d,
	0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61,
	0x6d, 0x70, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x65, 0x6f, 0x70, 0x6c, 0x65, 0x4e, 0x75, 0x6d, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x70, 0x65, 0x6f, 0x70, 0x6c, 0x65, 0x4e, 0x75, 0x6d,
	0x22, 0x25, 0x0a, 0x09, 0x42, 0x61, 0x73, 0x69, 0x63, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2e, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_emcs_proto_rawDescOnce sync.Once
	file_emcs_proto_rawDescData = file_emcs_proto_rawDesc
)

func file_emcs_proto_rawDescGZIP() []byte {
	file_emcs_proto_rawDescOnce.Do(func() {
		file_emcs_proto_rawDescData = protoimpl.X.CompressGZIP(file_emcs_proto_rawDescData)
	})
	return file_emcs_proto_rawDescData
}

var file_emcs_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_emcs_proto_goTypes = []interface{}{
	(*ApiLogRequest)(nil),    // 0: emcs.ApiLogRequest
	(*ApiLogResp)(nil),       // 1: emcs.ApiLogResp
	(*NumUploadRequest)(nil), // 2: emcs.NumUploadRequest
	(*BasicResp)(nil),        // 3: emcs.BasicResp
}
var file_emcs_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_emcs_proto_init() }
func file_emcs_proto_init() {
	if File_emcs_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_emcs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApiLogRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_emcs_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApiLogResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_emcs_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NumUploadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_emcs_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BasicResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_emcs_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_emcs_proto_goTypes,
		DependencyIndexes: file_emcs_proto_depIdxs,
		MessageInfos:      file_emcs_proto_msgTypes,
	}.Build()
	File_emcs_proto = out.File
	file_emcs_proto_rawDesc = nil
	file_emcs_proto_goTypes = nil
	file_emcs_proto_depIdxs = nil
}
